//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Resource.rc
//
#define IDD_DIALOG_I2C_DETECT           101
#define IDD_DIALOG_OPENAURASDK          103
#define IDC_COMBO_I2C_BUS               1001
#define IDC_BUTTON_I2C_DETECT           1002
#define IDC_EDIT_I2C_DETECT             1003
#define IDC_BUTTON_OPENAURASDK_I2CDETECT 1004
#define IDC_RADIO_OPENAURASDK_DIRECT_MODE 1006
#define IDC_RADIO_OPENAURASDK_EFFECT_MODE 1007
#define IDC_RADIO_OPENAURASDK_EFFECT_STATIC 1008
#define IDC_RADIO_OPENAURASDK_EFFECT_OFF 1009
#define IDC_RADIO_OPENAURASDK_EFFECT_BREATHING 1010
#define IDC_RADIO_OPENAURASDK_EFFECT_FLASHING 1011
#define IDC_RADIO_OPENAURASDK_EFFECT_SPECTRUM_CYCLE 1012
#define IDC_RADIO_OPENAURASDK_EFFECT_RAINBOW 1013
#define IDC_RADIO_OPENAURASDK_BREATHING_SPECTRUM 1014
#define IDC_RADIO_OPENAURASDK_EFFECT_CHASE_FADE 1015
#define IDC_EDIT_OPENAURASDK_LED_0_R    1016
#define IDC_EDIT_OPENAURASDK_LED_0_G    1017
#define IDC_EDIT_OPENAURASDK_LED_0_B    1018
#define IDC_BUTTON_OPENAURASDK_SET_COLORS_ALL 1019
#define IDC_COMBO_OPENAURASDK_DEVICE    1020
#define IDC_EDIT_OPENAURASDK_LED_1_R    1021
#define IDC_EDIT_OPENAURASDK_LED_1_G    1022
#define IDC_EDIT_OPENAURASDK_LED_1_B    1023
#define IDC_EDIT_OPENAURASDK_LED_2_R    1024
#define IDC_EDIT_OPENAURASDK_LED_2_G    1025
#define IDC_EDIT_OPENAURASDK_LED_2_B    1026
#define IDC_EDIT_OPENAURASDK_LED_3_R    1027
#define IDC_EDIT_OPENAURASDK_LED_3_G    1028
#define IDC_EDIT_OPENAURASDK_LED_3_B    1029
#define IDC_EDIT_OPENAURASDK_LED_4_R    1030
#define IDC_EDIT_OPENAURASDK_LED_4_G    1031
#define IDC_EDIT_OPENAURASDK_LED_4_B    1032
#define IDC_BUTTON1                     1033
#define IDC_BUTTON_OPENAURASDK_DUMP     1033
#define IDC_BUTTON_OPENAURASDK_SET_COLORS2 1034
#define IDC_BUTTON_OPENAURASDK_SET_COLORS 1034
#define IDC_BUTTON_OPENAURASDK_SET_ZONE 1034
#define IDC_COMBO_OPENAURASDK_DEVICE2   1035
#define IDC_COMBO_OPENAURASDK_MODE      1035
#define IDC_COMBO_OPENAURASDK_ZONE      1036

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        105
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1034
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
